### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by babyrig** [sandybradley/FTX_Market_Maker#1]
Hello sir !

First I want to thank you for this :)
Give me your DOGEBEAR address from FTX I will sent you some.

My issue after while (few hours):

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/dist-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Simple_FTX_MM.py", line 281, in <module>
    loop.run_until_complete(ws_fills(json.dumps(msg)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Simple_FTX_MM.py", line 58, in ws_fills
    message = json.loads(await websocket.recv())
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

I found this similar behavior I don't know if this can be implemented in your code or if are my side (tried on two different locations EC2 and vps)

https://stackoverflow.com/questions/54101923/1006-connection-closed-abnormally-error-with-python-3-7-websockets

Cheers

**Comment by sandybradley** [comment]
My FTX DOGEBEAR address:
0x33EE85787Ff6a443cbEA2CBAB4E8E26CcDf69A7b

I think the best solution for this connection drop is to auto reconnect.
The best way to do this is run your script as a subprocess in a separate
script. For example if your current script is called Simple_FTX_MM.py then
you can run another script to manage it like,

from subprocess import run
from time import sleep

# Path and name to the script you are trying to start
file_path = "Simple_FTX_MM.py"

restart_timer = 8


def start_script():
    try:
        # Make sure 'python' command is available
        run("python "+file_path, check=True)
    except:
        # Script crashed, lets restart it!
        handle_crash()


def handle_crash():
    sleep(restart_timer)  # Restarts the script after 2 seconds
    start_script()


start_script()

**Comment by babyrig** [comment]
Hello finally got you some DOGEBEAR transferred, was my first withdrawal please confirm/verify if have received in your wallet.

About the suggestion I tried without success, always got path not found when terminate the script, there is no way in the same script Simple_FTX_MM.py be in a loop when the error occur ?

Attemp to run inside the suggested script called keep.py the script is in the same directory I have tried with just the script name Simple_FTX_MM.py and with the full path, searched about it and all the examples was just about shell commands not another python script inside, so I don't know what to do next.

python3 keep.py

CTraceback (most recent call last):
  File "keep.py", line 18, in start_script
    run("python3 "+file_path, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3 Simple_FTX_MM.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keep.py", line 31, in <module>
    start_script()
  File "keep.py", line 23, in start_script
    handle_crash()
  File "keep.py", line 27, in handle_crash
    sleep(restart_timer)  # Restarts the script after 2 seconds
KeyboardInterrupt

**Comment by sandybradley** [comment]
Received your DOGEBEAR. Thank you.

Looks like it should run if your files are in the same folder. I would
double check the file name is correct and your dependencies are up to date.

eg
pip3 install subprocess

Are you running on Windows / Linux / Mac ?

**Comment by babyrig** [comment]
I am running in the same folder, yes the dependencies shows OK because when not the script don't start and fail due lack of dependecies. I am running on Ubuntu Linux 20.04.
Even with the full path instead of just the script name doesn't have worked eg /full/path/to/Simple_FTX_MM.py shows not found too:

FileNotFoundError: [Errno 2] No such file or directory: 'python3 /full/path/to/Simple_FTX_MM.py'

But I just tried with another way around using for as example below:

#for i in {1..9999}; do date ; echo $i times ;  python3 Simple_FTX_MM.py; done

output:
Tue Mar 16 17:41:46 UTC 2021
1 times
Opening websocket. Waiting for order fills
{'type': 'subscribed', 'channel': 'fills'}

**Comment by sandybradley** [comment]
Looks like you got it working another way. That's fine if it's working for
you, otherwise try changing the following.

run("python3 "+file_path, check=True)

to

run(['python3',file_path])

**Comment by babyrig** [comment]
After the change to run(['python3',file_path]) worked just fine.

It's possible to integrate in the Market Maker script a Telegram notification when orders be filled ?

Thanks

**Comment by sandybradley** [comment]
I'm not sure how to integrate with Telegram. Maybe someone else can help?
